### PR TITLE
patches to let gimp-plugin-astronomy be built in 2022

### PR DESCRIPTION
**Pull request by JoesCat**
Updates to more or less match prior releases, plus updates to current release to use more current configure.ac/Makefile.am and replaced intltool with current gettext.
Also added rpm spec file for rpm based distros.

These patches seem to builds ok with:
```
./configure
make
```
To build completely from the beginning, use:
```
autoreconf -ivs
automake
./configure
make
```
making a dist file, use `make dist`

### CODE REVIEW

**Comment by JoesCat** [comment]
Thanks for the merge - glad to see you're active.

**Comment by JoesCat** [comment]
Are you able to fetch other patches?
https://github.com/JoesCat/gimp-plugin-astronomy/network
 I did them as master, since I had seen no activity for a while with your code, or hennig's

**Comment by prokoudine** [comment]
Hi, thank you! Unfortunately, applying your entire patchset results in this being executed over and over and over again:

```
cd .. \
  && CONFIG_FILES=po/Makefile.in CONFIG_HEADERS= CONFIG_LINKS= \
       /bin/bash ./config.status
config.status: creating po/Makefile.in
config.status: executing depfiles commands
config.status: executing po-directories commands
config.status: creating po/POTFILES
config.status: creating po/Makefile

```

**Comment by zvezdochiot** [comment]
@prokoudine say:
> this being executed over and over and over again:

This behavior existed before the this patch.

**Comment by JoesCat** [comment]
Thanks for the info @prokoudine - that is good info.
I'm also guessing you're running ./autogen.sh ?

You may have better luck using:
```
aclocal --force
autoconf -f
automake --add-missing
./configure
make
```
Ideally, I would have preferred going the simpler route of:
```
autoreconf -i
automake
./configure
make
```
but the code isn't ready for that yet.
The code as it is right now is sort-of a compromise.
1) I saw no replies from your website for a year, or from Henning's website when I emailed the address on the website asked about patching, but at the same time I wanted to get this project up and working for Mageia 9 (It was accepted into Mageia 9 as 0.11): https://repology.org/project/gimp:astronomy/versions

2) keeping these initial updates to a minimum (because too many changes makes it harder to accept a fork).
You could see some problems if you read more here: https://bugs.mageia.org/show_bug.cgi?id=30931

The next steps (from my point of view) would be to avoid adding AM_GNU_GETTEXT_REQUIRE_VERSION([version]) in configure.ac and to fix the po/makefile.am stuff so that building this project could be handled simply using:
```
autoreconf -i
automake
./configure
make
```
To do this, gimp-plugin-astronomy would need to adopt something similar to what was done with FontForge:
https://github.com/fontforge/fontforge/blob/2.0.20140101/po/Makefile.am
and updating gimp-plugin-astronomy from GPL2+ to GPL3+

or if you want to maintain GPL2+, look at gimp-wavelet-denoise which also does a similar process, but would need adapting into a Makefile.am
https://github.com/JoesCat/gimp-wavelet-denoise/blob/master/po/Makefile

At this point, then I think the code should work fine using 'autoreconf -i', which was my target after release/tagpoint 0.11.

If you're willing to delete your merge you made yesterday, and then add the patches (and timestamps) so that we're all on the same identical fork (up to, or beyond tagpoint 0.11, accepted by Mageia 9), I think we could 'all' be on the same starting point to add code into a common fork, and fix gimp-plugin-astronomy.

FYI - gimp-plugin-astronomy could use more updates... but...
...at the moment, I'm chasing some other patches in another (different) project that I'd like to hopefully get accepted and merged soon.

Thanks for your feedback,
Joe

**Comment by prokoudine** [comment]
@JoesCat Yes, I was using ./autogen.sh, which is what I've learned to do :)

Do you want commit access to this repo?

**Comment by JoesCat** [comment]
Yes - Projects tend to have an advantage when more people work on the project.
No - if I'm the only one working on it, there would be no advantage working alone in another fork by myself.

First thing I see that needs fixing is to get your repo to match-up to at least tag 0.11

**Pull request merged**
